CREATE USER CRM4telecom IDENTIFIED BY CRM4telecom DEFAULT TABLESPACE users QUOTA 
100m ON users TEMPORARY TABLESPACE temp; 

GRANT CREATE SESSION TO crm4telecom; 

GRANT CREATE ANY TABLE TO crm4telecom; 

GRANT ALTER ANY TABLE TO crm4telecom; 

GRANT DROP ANY TABLE TO crm4telecom; 